### PR TITLE
Add String method for Axis.

### PR DESCRIPTION
**Pull request by adlerjohn**
At @Wondertan's request.

### CODE REVIEW

**Comment by Wondertan** [comment]
You can now remove the switch we introduced in last PR @adlerjohn

**Comment by adlerjohn** [comment]
Don't we still need this `switch` to be able to identify which axis the error is for? The `String()` method should just be for printing out.

https://github.com/celestiaorg/rsmt2d/blob/35efa74fe884a5cbcdd90a8c410b5ffaeaa82770/extendeddatacrossword.go#L39-L46

**Comment by adlerjohn** [comment]
Why remove this `switch`? It's for printing out the error.

https://github.com/celestiaorg/rsmt2d/blob/35efa74fe884a5cbcdd90a8c410b5ffaeaa82770/extendeddatacrossword.go#L39-L46

**Review by liamsi — APPROVED** [review]
I don't like that this and the prev. PR slightly decreased test-coverage but this lgtm but this is not blocking merging this PR. 

I also don't understand why switch in Axis.String() replaces the switch-case in ErrByzantineData.Error() as per Hlib's comment.

**Comment by Wondertan** [comment]
@adlerjohn, @liamsi. The switch can be removed with:
 `return fmt.Sprintf("byzantine %s: %d", e.Axis, e.Index) `

**Comment by adlerjohn** [comment]
Ah now I get it. Fixed in [609541b](https://github.com/celestiaorg/rsmt2d/pull/81/commits/609541b4cd7da14a539a8d6c27efb47170121d74)

**Pull request merged**
